services:
  web:
    build:
      context: .
      target: runner
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8000}
    ports:
      - "${APP_PORT:-3000}:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8000}
      - USUARIOS_SERVICE_URL=${USUARIOS_SERVICE_URL:-http://localhost:8001}
      - AUTH_JWT_SECRET=${AUTH_JWT_SECRET}
      - PACIENTES_SERVICE_URL=${PACIENTES_SERVICE_URL:-http://localhost:8002}
    restart: unless-stopped

  web-dev:
    build:
      context: .
      target: development
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8000}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "${APP_PORT:-3000}:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8000}
      - USUARIOS_SERVICE_URL=${USUARIOS_SERVICE_URL:-http://localhost:8001}
      - AUTH_JWT_SECRET=${AUTH_JWT_SECRET}
      - PACIENTES_SERVICE_URL=${PACIENTES_SERVICE_URL:-http://localhost:8002}
    profiles:
      - dev
